dist: trusty
language: node_js
node_js:
  - "7"
env:
  - EMBER_VERSION=default
jobs:
  fast_finish: true
  allow_failures:
    - env: EMBER_VERSION=release

before_install:
  - "npm install -g npm@^2"
install:
  - npm install
script:
  - npm test
